version: '2.2'

services:
  apache:
    image: hammermc/nominatim-docker
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersecret
    command: apache2
    volumes:
      - data:/data
      - run:/run
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/local.php:/Nominatim/build/settings/local.php
    tmpfs:
      - /tmp
    ports:
      - 80:80
    depends_on:
      - initdb

  postgres:
    image: hammermc/nominatim-docker
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - data:/data
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - run:/run
    tmpfs:
      - /tmp

  initdb:
    image: hammermc/nominatim-docker
    restart: "no"
    command: initdb
    environment:
      - POSTGRES_PASSWORD=supersecret
      - OSM_PBF_URL=http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf
      - OSM2PGSQLCACHE=20000 #20gigs used only during init
      - REDOWNLOAD
      - REINITDB
    volumes:
      - data:/data
      - run:/run
    tmpfs:
      - /tmp
    depends_on:
      - postgres

volumes:
  data:
  postgres-data:
  run:

